---

- name: Fetch current cluster config
  shell: 'kops get cluster --name {{ cluster_name }} -o yaml > /tmp/{{ cluster_name }}-cluster-conf.yaml'
  changed_when: false

- name: Configure IAM ContainerRegistry 
  lineinfile:
    path: /tmp/{{ cluster_name }}-cluster-conf.yaml
    regexp: '^(\s+)allowContainerRegistry:'
    line: '\1allowContainerRegistry: {{ iam.allow_container_registry }}'
    backrefs: yes
  when: iam.allow_container_registry is defined
  notify: 'Push cluster config'

- name: Configure IAM legacy 
  lineinfile:
    path: /tmp/{{ cluster_name }}-cluster-conf.yaml
    regexp: '^(\s+)legacy:'
    line: '\1legacy: {{ iam.legacy }}'
    backrefs: yes
  when: iam.legacy is defined
  notify: 'Push cluster config'

- name: Run handlers
  meta: flush_handlers
